// src/views/js-test/index.vue
<script setup lang="ts">
import { ref } from 'vue';
import { exec } from '@/common/exec';
import PlayGround from '@/components/PlayGround.vue';

const codeContent = ref('');
const codeOptions = ref<any[]>([]);

const codes = import.meta.glob<string>('./codes/**/*.js', {
  eager: true,
  query: 'raw',
  import: 'default',
});
codeOptions.value = Object.keys(codes).map((key) => ({
  value: key,
  label: key,
  content: codes[key],
}));

function handleEval(code: string) {
  exec(code);
}
</script>

<template>
  <PlayGround
    v-model="codeContent"
    :code-options="codeOptions"
    @eval="handleEval"
  >
    <div id="jslog-container"></div>
  </PlayGround>
</template>

<script lang="ts">
export const meta = { title: 'js测试' };
</script>

// apps/react-test/src/views/js-test/index.tsx
import { useState } from 'react';
import { exec } from '@web-test/common';
import PlayGround from '@/components/PlayGround';

const codes = import.meta.glob<string>('./codes/**/*.js', {
  eager: true,
  query: 'raw',
  import: 'default',
});

function Test() {
  const [codeContent, setCodeContent] = useState('');
  const [codeOptions] = useState<any[]>(() =>
    Object.keys(codes).map((key) => ({
      value: key,
      label: key,
      content: codes[key],
    }))
  );
  function handleEval(code: string) {
    exec(code);
  }
  return (
    <PlayGround value={codeContent} codeOptions={codeOptions} onChange={setCodeContent} onEvel={handleEval}>
      <div id="jslog-container" className="flex-1"></div>
    </PlayGround>
  );
}

export default Test;
