// apps/react-test/src/components/MonacoEditor.tsx
import { useEffect, useRef } from 'react';
import * as monaco from 'monaco-editor';
import '@/common/initMonaco';

type Props = {
  value: string;
  onChange: (val: string) => void;
  editorOptions?: any;
};

const defaultOptions = {
  automaticLayout: true,
  tabSize: 2,
  language: 'javascript',
};

function MonacoEditor(props: Props) {
  const editor = useRef<monaco.editor.IStandaloneCodeEditor>(null);
  const editorDom = useRef<HTMLDivElement>(null);
  function initEditor() {
    if (editor.current) {
      return;
    }
    editor.current = monaco.editor.create(editorDom.current!, Object.assign({ ...defaultOptions }, props.editorOptions));
    editor.current?.onDidChangeModelContent(() => {
      props.onChange(editor.current?.getValue() ?? '');
    });
  }
  useEffect(() => {
    const editorValue = editor.current?.getValue();
    if (editorValue === props.value) {
      return;
    }
    editor.current?.setValue(props.value);
  }, [props.value]);
  useEffect(() => {
    initEditor();
  });
  return <div ref={editorDom} className="flex-1 min-w-0 min-h-0"></div>;
}

export default MonacoEditor;

// apps/vue-test/src/components/MonacoEditor.vue
<script setup lang="ts">
import { onMounted, ref, shallowRef, watch } from 'vue';
import * as monaco from 'monaco-editor';
import '@/common/initMonaco';

const props = withDefaults(
  defineProps<{
    editorOptions?: any;
  }>(),
  {
    editorOptions: () => ({}),
  }
);
const modelValue = defineModel<string>({ default: '' });

const defaultOptions = {
  automaticLayout: true,
  tabSize: 2,
  language: 'javascript',
};

const editor = shallowRef<monaco.editor.IStandaloneCodeEditor>();

const editorDom = ref<HTMLDivElement>();

function initEditor() {
  if (editor.value) {
    return;
  }
  editor.value = monaco.editor.create(editorDom.value!, Object.assign({ ...defaultOptions }, props.editorOptions));
  watch(
    () => modelValue.value,
    (val) => {
      const editorValue = editor.value?.getValue();
      if (editorValue === val) {
        return;
      }
      editor.value?.setValue(modelValue.value);
    },
    {
      immediate: true,
    }
  );
  editor.value?.onDidChangeModelContent(() => {
    modelValue.value = editor.value?.getValue() ?? '';
  });
}
onMounted(() => {
  initEditor();
});

defineExpose({
  editor,
});
</script>

<template>
  <div ref="editorDom" class="flex-1 min-w-0 min-h-0"></div>
</template>
